### ISSUE TITLE
I can not install

### ISSUE THREAD

**Issue by halatef** [AlanBell/LSRelated#1]
Guys
I am using Vtiger 6.4, and i can not install this module
I got the following error

dUnzip2: File 'manifest.xml' is not compressed in the zip.
FailedInvalid File provided for module import! Try Again.

**Comment by AlanBell** [comment]
so in your zip file is the manifest.xml in the top level?

**Comment by AlanBell** [comment]
if you downloaded a zip from github that won't work as it puts everything in a folder inside the zip. Rezip it without the folder and it should install fine.
